### ISSUE TITLE
[GH Request] Add edx_transifex_bot as administrator to frontend-app-discussions repo

### ISSUE THREAD

**Issue by jristau1984** [openedx/tcril-engineering#397] opened 2022-08-01 13:53 UTC
### Firm Name

2U

### Urgency

Medium Urgency (resolve in <one week)

### Requested Change

Our translation documentation directs us to add the user "edx_transifex_bot" as an administrator to the frontend-app-discussions repo in order for it to be able to merge unreviewed pull requests.  

### Reasoning

Infinity team needs translations in the new discussions experience.

If this is still the appropriate guidance, then please add this user as an admin (I cannot find an option for that myself, so I do not think I have permissions to do it self-service)

If this is NOT the appropriate guidance, please let me know so I can update our documentation and request the correct change.

**Comment by ormsbee** [comment] 2022-08-01 22:58
@jristau1984: Added [edx-transifex-bot](https://github.com/edx-transifex-bot) (dashes, not underscores) to be admin on [frontend-app-discussions](https://github.com/openedx/frontend-app-discussions). Please let me know if something else was intended.

@Carlos-Muniz (as our translations expert): Does this seem correct to you?

**Comment by ormsbee** [comment] 2022-08-02 14:27
> Based on the edx-transifex-translations group's description and its ability to function as intended in other repos with just write access, I think it is sufficient to add the frontend-app-discussions repo to the edx-transifex-translations group.

@jristau1984: Would this work for you instead, or is there a definite need for admin-level rights for this user?

**Comment by ormsbee** [comment] 2022-08-05 14:39
@jristau1984: Based on Carlos's recommendations, I've removed edx-transifex-bot from frontend-app-discussions and instead given the edx-transifex-translations group write access to frontend-app-discussions. If this is insufficient, please re-open this ticket. Thank you!

**Comment by saadyousafarbi** [comment] 2022-08-25 10:19
Hello @ormsbee @Carlos-Muniz 
Im reaching out on this issue as we are still facing issues with the `edx-transifex-bot` being unable to merge unreviewed Pull Requests into the `frontend-app-discussions` repo. The repo is setup to have a review on a PR, before it can be merged.
Can it be that the bot still requires to be added to `frontend-app-discussions` and given admin-level rights? 
Let me know if you need any more information regarding this. Thank you!

**Comment by ormsbee** [comment] 2022-08-26 15:13
@saadyousafarbi: Okay, I raised the permissions to admin. Please try again?

**Comment by saadyousafarbi** [comment] 2022-09-01 15:56
Thanks @ormsbee 
It is now working as expected!

**Closed** 2022-09-06 16:26 UTC
Labels: github-request
