### ISSUE TITLE
Upgrade 3 Apps Using the Heroku 18 stack

### ISSUE THREAD

**Issue by e0d** [openedx/tcril-engineering#408] opened 2022-08-09 11:47 UTC
> The Heroku-18 stack is deprecated
> You have 4 apps in this team that are using the Heroku-18 stack, which is deprecated. From April 30th, 2023, Heroku-18 will be end-of-life and no longer receive security updates. From May 1st, 2023, builds will be disabled. Please upgrade your apps to a newer Heroku stack. [ Visit here to learn more](https://help.heroku.com/X5OE6BCA/heroku-18-end-of-life-faq)

The apps in questions are:

[openedx-pr-watcher-notifier](https://dashboard.heroku.com/apps/openedx-pr-watcher-notifier) [Python](https://dashboard.heroku.com/apps/openedx-pr-watcher-notifier/settings) [heroku-18](https://dashboard.heroku.com/apps/openedx-pr-watcher-notifier/settings)

openedx-webhooks heroku-18

[openedxstats](https://dashboard.heroku.com/apps/openedxstats) [Python](https://dashboard.heroku.com/apps/openedxstats/settings [heroku-18](https://dashboard.heroku.com/apps/openedxstats/settings) [United States (https://dashboard.heroku.com/apps/openedxstats/settings)

**Comment by feanil** [comment] 2022-11-14 20:50
Closing because this is a duplicate of https://github.com/openedx/tcril-engineering/issues/454

**Closed by feanil** 2022-11-14 20:50 UTC
Labels: maintenance
