### ISSUE TITLE
[GH Request] <ADD A REQUEST TITLE HERE>

### ISSUE THREAD

**Issue by connollymj13** [openedx/tcril-engineering#470] opened 2022-09-23 18:31 UTC
### Firm Name

tCRIL

### Urgency

Low Urgency 

### Requested Change

Hi,

I am requesting that Shahroz Ahmad (username: ishahroz) be added to Arbisoft CLA.

### Reasoning

They are a new contractor who will be doing Maintenance and improvement of front end code used for [edx.org](https://edx.org/) (security patches, automating routine tasks, replacing legacy code, etc.)

**Comment by e0d** [comment] 2022-09-23 19:11
Hello @connollymj13, I believe this position will be working on edX's FED BOM team, is that right?  If so, we will need 2U IT to make that request to add you on their behalf.  This is our standard process.  The 2U manager should be able to help with this.

@georgebabey

**Comment by nedbat** [comment] 2022-09-24 15:24
@connollymj13 to help others in the future, was there a page directing you to create this issue? We can add clarifications there.

**Comment by e0d** [comment] 2022-10-04 15:02
@nedbat I'm planning to close tomorrow unless there's an update.

**Comment by nedbat** [comment] 2022-10-05 11:55
@e0d looks like another kind of process friction.  I wanted to tag George on this issue, but can't, I guess because he's not in this repo?

**Comment by e0d** [comment] 2022-10-05 13:09
If you type out his handle it works, I'm not sure the root cause, but we
can add something to investigate.

**Comment by nedbat** [comment] 2022-10-05 13:26
@georgebabey (OK, I didn't know the handle, and tabbing even after typing it completely borks it...)

**Comment by jmbowman** [comment] 2022-10-05 14:29
He should have already been added to the CLA 5 days ago via https://github.com/openedx/tcril-engineering/issues/462 (which also hit some process issues along the way).

**Comment by e0d** [comment] 2022-10-05 18:51
Yes, he's already been added.  I'm going to close this, but it would be useful to have an answer to @nedbat 's original question in this issue.

**Closed by e0d** 2022-10-05 18:51 UTC
Labels: github-request
